# Generated by Django 5.2.1 on 2025-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('application_type', models.CharField(max_length=10)),
            ],
        ),
    ]
