# Generated by Django 5.1.5 on 2025-02-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='required_documents',
            field=models.ManyToManyField(to='common.documenttype'),
        ),
    ]
