# Generated by Django 5.1.5 on 2025-02-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_required_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='applicant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.applicanttype', to_field='name'),
        ),
    ]
