# Generated by Django 5.1.5 on 2025-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_documenttype_name'),
        ('students', '0003_alter_student_applicant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='required_documents',
            field=models.ManyToManyField(blank=True, null=True, to='common.documenttype'),
        ),
    ]
