# Generated by Django 5.2.1 on 2025-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
