# Generated by Django 5.1.5 on 2025-02-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fails',
        ),
        migrations.AddField(
            model_name='documentpassfail',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_pass_fails', to='documents.document'),
        ),
    ]
