# Generated by Django 5.2.1 on 2025-06-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecordEvaluationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('ocr_text', models.TextField(null=True)),
                ('file', models.URLField()),
                ('memo', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('interview_questions', models.TextField(null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('evaluation_category', models.ForeignKey(db_column='evaluation_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_records.studentrecordevaluationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='student_records.studentrecordevaluationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='student_records.studentrecordevaluationquestion')),
                ('student_record', models.ForeignKey(db_column='student_record_id', on_delete=django.db.models.deletion.CASCADE, to='student_records.studentrecord')),
            ],
        ),
    ]
