# Generated by Django 5.1.5 on 2025-02-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0001_initial'),
        ('students', '0002_student_required_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='students.student'),
        ),
    ]
