# Generated by Django 5.1.5 on 2025-02-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_documenttype_name'),
        ('student_records', '0002_alter_studentrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.documenttype'),
        ),
    ]
