# Generated by Django 5.2.1 on 2025-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0002_alter_studentrecord_file_alter_studentrecord_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentrecord',
            table='student_record',
        ),
        migrations.AlterModelTable(
            name='studentrecordevaluationcategory',
            table='student_record_evaluation_category',
        ),
        migrations.AlterModelTable(
            name='studentrecordevaluationquestion',
            table='student_record_evaluation_question',
        ),
        migrations.AlterModelTable(
            name='studentrecordevaluationscore',
            table='student_record_evaluation_score',
        ),
    ]
