# Generated by Django 5.2.1 on 2025-06-06 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0003_alter_studentrecord_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecordevaluationscore',
            name='student_record',
            field=models.ForeignKey(db_column='student_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scores', to='student_records.studentrecord'),
        ),
    ]
