# Generated by Django 5.1.5 on 2025-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0003_alter_studentrecord_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='score3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='score4',
            field=models.IntegerField(default=0),
        ),
    ]
