# Generated by Django 5.1.5 on 2025-02-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0004_studentrecord_score1_studentrecord_score2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='score1',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score2',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score3',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score4',
            field=models.IntegerField(default=None),
        ),
    ]
