# Generated by Django 5.2.1 on 2025-06-08 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0004_alter_studentrecordevaluationscore_student_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecordevaluationquestion',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_questions', to='student_records.studentrecordevaluationcategory'),
        ),
    ]
