# Generated by Django 5.2.1 on 2025-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0005_alter_studentrecordevaluationquestion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
