# Generated by Django 5.2.1 on 2025-06-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayEvaluationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('range_score', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('ocr_text', models.TextField(null=True)),
                ('file', models.URLField()),
                ('summary', models.TextField(null=True)),
                ('score_by_length', models.IntegerField(null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='essays.essayevaluationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EssayEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='essays.essayevaluationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EssayEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True)),
                ('essay', models.ForeignKey(db_column='essay_id', on_delete=django.db.models.deletion.CASCADE, to='essays.essay')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='essays.essayevaluationquestion')),
            ],
        ),
    ]
