# Generated by Django 5.2.1 on 2025-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='essay',
            table='essay',
        ),
        migrations.AlterModelTable(
            name='essayevaluationcategory',
            table='essay_evaluation_category',
        ),
        migrations.AlterModelTable(
            name='essayevaluationquestion',
            table='essay_evaluation_question',
        ),
        migrations.AlterModelTable(
            name='essayevaluationscore',
            table='essay_evaluation_score',
        ),
    ]
