# Generated by Django 5.1.5 on 2025-02-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_alter_essay_evaluation_remove_essaycriteria_content_and_more'),
        ('students', '0002_student_required_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='students.student'),
        ),
        migrations.AlterField(
            model_name='essayscore',
            name='criteria_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_scores', to='essays.criteriaitem'),
        ),
        migrations.AlterField(
            model_name='essayscore',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_scores', to='essays.essay'),
        ),
    ]
