# Generated by Django 5.2.1 on 2025-06-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_alter_essay_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayevaluationscore',
            name='essay',
            field=models.ForeignKey(db_column='essay_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scores', to='essays.essay'),
        ),
    ]
